


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axis01_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axis01_vip_VIP_INTERFACE_MODE     = 0;
      parameter axis01_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter axis01_vip_VIP_DATA_WIDTH         = 32;
      parameter axis01_vip_VIP_ID_WIDTH           = 0;
      parameter axis01_vip_VIP_DEST_WIDTH         = 0;
      parameter axis01_vip_VIP_USER_WIDTH         = 0;
      parameter axis01_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter axis01_vip_VIP_HAS_TREADY         = 1;
      parameter axis01_vip_VIP_HAS_TSTRB          = 0;
      parameter axis01_vip_VIP_HAS_TKEEP          = 1;
      parameter axis01_vip_VIP_HAS_TLAST          = 1;
      parameter axis01_vip_VIP_HAS_ACLKEN         = 0;
      parameter axis01_vip_VIP_HAS_ARESETN        = 0;
///////////////////////////////////////////////////////////////////////////
typedef axi4stream_mst_agent #(axis01_vip_VIP_SIGNAL_SET, 
                        axis01_vip_VIP_DEST_WIDTH,
                        axis01_vip_VIP_DATA_WIDTH,
                        axis01_vip_VIP_ID_WIDTH,
                        axis01_vip_VIP_USER_WIDTH, 
                        axis01_vip_VIP_USER_BITS_PER_BYTE,
                        axis01_vip_VIP_HAS_ARESETN) axis01_vip_mst_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axis01_vip_mst_t  axis01_vip_mst;
//      initial begin : START_axis01_vip_MASTER
//        axis01_vip_mst = new("axis01_vip_mst", `axis01_vip_PATH_TO_INTERFACE);
//        axis01_vip_mst.start_master();
//      end



endpackage : axis01_vip_pkg
