


///////////////////////////////////////////////////////////////////////////
//NOTE: This file has been automatically generated by Vivado.
///////////////////////////////////////////////////////////////////////////
`timescale 1ps/1ps
package axis00_vip_pkg;
import axi4stream_vip_pkg::*;
///////////////////////////////////////////////////////////////////////////
// These parameters are named after the component for use in your verification 
// environment.
///////////////////////////////////////////////////////////////////////////
      parameter axis00_vip_VIP_INTERFACE_MODE     = 2;
      parameter axis00_vip_VIP_SIGNAL_SET         = 8'b00011011;
      parameter axis00_vip_VIP_DATA_WIDTH         = 512;
      parameter axis00_vip_VIP_ID_WIDTH           = 0;
      parameter axis00_vip_VIP_DEST_WIDTH         = 0;
      parameter axis00_vip_VIP_USER_WIDTH         = 0;
      parameter axis00_vip_VIP_USER_BITS_PER_BYTE = 0;
      parameter axis00_vip_VIP_HAS_TREADY         = 1;
      parameter axis00_vip_VIP_HAS_TSTRB          = 0;
      parameter axis00_vip_VIP_HAS_TKEEP          = 1;
      parameter axis00_vip_VIP_HAS_TLAST          = 1;
      parameter axis00_vip_VIP_HAS_ACLKEN         = 0;
      parameter axis00_vip_VIP_HAS_ARESETN        = 0;
///////////////////////////////////////////////////////////////////////////


typedef axi4stream_slv_agent #(axis00_vip_VIP_SIGNAL_SET, 
                        axis00_vip_VIP_DEST_WIDTH,
                        axis00_vip_VIP_DATA_WIDTH,
                        axis00_vip_VIP_ID_WIDTH,
                        axis00_vip_VIP_USER_WIDTH, 
                        axis00_vip_VIP_USER_BITS_PER_BYTE,
                        axis00_vip_VIP_HAS_ARESETN) axis00_vip_slv_t;
      
///////////////////////////////////////////////////////////////////////////
// How to start the verification component
///////////////////////////////////////////////////////////////////////////
//      axis00_vip_slv_t  axis00_vip_slv;
//      initial begin : START_axis00_vip_SLAVE
//        axis00_vip_slv = new("axis00_vip_slv", `axis00_vip_PATH_TO_INTERFACE);
//        axis00_vip_slv.start_slave();
//      end

endpackage : axis00_vip_pkg
