// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "write_stream_512_512_s.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic write_stream_512_512_s::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic write_stream_512_512_s::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<1> write_stream_512_512_s::ap_ST_fsm_state1 = "1";
const sc_lv<32> write_stream_512_512_s::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool write_stream_512_512_s::ap_const_boolean_1 = true;

write_stream_512_512_s::write_stream_512_512_s(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( axis00_TREADY );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( axis00_TREADY );
    sensitive << ( ap_ce );

    SC_METHOD(thread_axis00_TDATA);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( acc_data_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_axis00_TDATA_blk_n);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( axis00_TREADY );

    SC_METHOD(thread_axis00_TKEEP);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( acc_keep_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_axis00_TLAST);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( acc_last_V_read );
    sensitive << ( ap_ce );

    SC_METHOD(thread_axis00_TVALID);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( axis00_TREADY );
    sensitive << ( ap_ce );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( axis00_TREADY );
    sensitive << ( ap_ce );

    ap_CS_fsm = "1";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "write_stream_512_512_s_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, acc_data_V_read, "(port)acc_data_V_read");
    sc_trace(mVcdFile, acc_keep_V_read, "(port)acc_keep_V_read");
    sc_trace(mVcdFile, acc_last_V_read, "(port)acc_last_V_read");
    sc_trace(mVcdFile, axis00_TDATA, "(port)axis00_TDATA");
    sc_trace(mVcdFile, axis00_TVALID, "(port)axis00_TVALID");
    sc_trace(mVcdFile, axis00_TREADY, "(port)axis00_TREADY");
    sc_trace(mVcdFile, axis00_TKEEP, "(port)axis00_TKEEP");
    sc_trace(mVcdFile, axis00_TLAST, "(port)axis00_TLAST");
    sc_trace(mVcdFile, axis00_TDATA_blk_n, "(port)axis00_TDATA_blk_n");
    sc_trace(mVcdFile, ap_ce, "(port)ap_ce");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

write_stream_512_512_s::~write_stream_512_512_s() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void write_stream_512_512_s::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
}

void write_stream_512_512_s::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void write_stream_512_512_s::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
          !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis00_TREADY.read())) && 
          esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void write_stream_512_512_s::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void write_stream_512_512_s::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis00_TREADY.read())) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void write_stream_512_512_s::thread_axis00_TDATA() {
    axis00_TDATA = acc_data_V_read.read();
}

void write_stream_512_512_s::thread_axis00_TDATA_blk_n() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        axis00_TDATA_blk_n = axis00_TREADY.read();
    } else {
        axis00_TDATA_blk_n = ap_const_logic_1;
    }
}

void write_stream_512_512_s::thread_axis00_TKEEP() {
    axis00_TKEEP = acc_keep_V_read.read();
}

void write_stream_512_512_s::thread_axis00_TLAST() {
    axis00_TLAST = acc_last_V_read.read();
}

void write_stream_512_512_s::thread_axis00_TVALID() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
         !(esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) || esl_seteq<1,1,1>(ap_const_logic_0, axis00_TREADY.read())) && 
         esl_seteq<1,1,1>(ap_ce.read(), ap_const_logic_1))) {
        axis00_TVALID = ap_const_logic_1;
    } else {
        axis00_TVALID = ap_const_logic_0;
    }
}

void write_stream_512_512_s::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            ap_NS_fsm = ap_ST_fsm_state1;
break;
        default : 
            ap_NS_fsm = "X";
            break;
    }
}

}

